let sectorsSubSectors = {
  'Textile and apparels': [
    'Cutting master',
    'Button operator',
    'Trimming staff',
    'Finishing Helper',
    'Machine Mechanic',
    'Qc checker',
    'Button hole operator',
    'Iron machine operators',
    'Tailor',
    'Helper',
  ],
  'Food and dining': [
    'Chef',
    'Waiter',
    'Receptionist',
    'Sous chef',
    'Commi chef',
    'Indian chef',
    'Chinese chef',
    'Arabic chef',
    'Continental chef',
  ],
  'Healthcare and wellness': [
    'Nurse',
    'Physiotherapist',
    'Nutritionist',
    'Psychiatrist',
    'Optometrist',
    'Pharmacist',
    'Doctor',
    'Lab technician',
    'OT assistant',
    'Ambulance driver',
    'Home nurse',
  ],
  Education: [
    'Subject experts',
    'Lab assistant',
    'Trainer',
    'Mentor',
    'Professor',
  ],
  'Computer and mobile': [
    'Computer technician',
    'Mobile technician',
    'Software developer',
    'Graphic designer',
  ],
  'Home care service': [
    'Electrician',
    'Plumber',
    'Carpenter',
    'Mason',
    'Gardener',
    'Home maid',
    'Painter',
    'Flooring',
  ],
  Automobile: [
    'Car mechanic',
    'Puncture repair',
    'Car painting',
    'Car denting work',
    'Car wash',
    'Detailing ',
    'Ceramic coating',
  ],
};

console.log(sectorsSubSectors['Automobile']);
